import time
print('Hello...')
time.sleep(0.1)
print('This will help you find the point definitions for time with Noodle Extensions.')
time.sleep(0.5)
d = input('Type total duration (beats) of the section.')
a = input('Enter the first beat you would like.')
b = input('Second beat.')
c = input('Third beat.')
print('Here are the beats you defined.')
print('{a},{b},{c}' .format(a=a, b=b, c=c))
at = (int(a)/int(d))
bt = (int(b)/int(d))
ct = (int(c)/int(d))
time.sleep(0.5)
print('Here are your values with time.')
print('All other point definitions are not included, only time.')
print(f'[0,0,0,{at}],[0,0,0,{bt}],[0,0,0,{ct}]')
input('Press any key to close.')